# Generated by Django 2.1.1 on 2018-09-17 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='update_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
