# Generated by Django 2.1.1 on 2018-09-23 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainManu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='一级分类菜单标题')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryManu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='二级分类菜单标题')),
                ('mainmanu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.MainManu')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='mainmanu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.MainManu'),
        ),
        migrations.AddField(
            model_name='article',
            name='secondarymanu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.SecondaryManu'),
        ),
        migrations.AddField(
            model_name='product',
            name='mainmanu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.MainManu'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondarymanu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.SecondaryManu'),
        ),
    ]
