# Generated by Django 2.1.1 on 2018-09-23 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180923_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='mainmanu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.MainManu', verbose_name='请设置一级分类'),
        ),
        migrations.AlterField(
            model_name='article',
            name='secondarymanu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.SecondaryManu', verbose_name='请设置二级分类'),
        ),
        migrations.AlterField(
            model_name='mainmanu',
            name='title',
            field=models.CharField(max_length=100, verbose_name='一级分类菜单标题'),
        ),
        migrations.AlterField(
            model_name='secondarymanu',
            name='title',
            field=models.CharField(max_length=100, verbose_name='二级分类菜单标题'),
        ),
    ]
