# Generated by Django 2.1.1 on 2018-09-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180923_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmanu',
            name='template',
            field=models.CharField(choices=[('AD', 'article_detail'), ('AL', 'article_list'), ('PL', 'product_list')], max_length=100, null=True, verbose_name='展示模版'),
        ),
    ]
