# Generated by Django 2.1.1 on 2018-09-24 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_mainmanu_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondarymanu',
            name='mainmanu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.MainManu', verbose_name='请设置一级分类'),
        ),
    ]
