# Generated by Django 2.1.1 on 2018-10-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20180924_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('telphone', models.CharField(max_length=20, verbose_name='电话')),
                ('email', models.CharField(max_length=20, verbose_name='邮箱')),
                ('remark', models.CharField(max_length=1000, verbose_name='备注')),
            ],
        ),
    ]
