# Generated by Django 2.1.1 on 2018-10-08 08:36

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_customerappraise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '资讯内容页', 'verbose_name_plural': '资讯内容页'},
        ),
        migrations.AlterModelOptions(
            name='consult',
            options={'verbose_name': '客户咨询', 'verbose_name_plural': '客户咨询'},
        ),
        migrations.AlterModelOptions(
            name='mainmanu',
            options={'verbose_name': '一级分类菜单', 'verbose_name_plural': '一级分类菜单'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '产品内容页', 'verbose_name_plural': '产品内容页'},
        ),
        migrations.AlterModelOptions(
            name='secondarymanu',
            options={'verbose_name': '二级分类菜单', 'verbose_name_plural': '二级分类菜单'},
        ),
        migrations.AlterField(
            model_name='customerappraise',
            name='customer_appraise',
            field=models.CharField(max_length=2000, verbose_name='评价内容'),
        ),
        migrations.AlterField(
            model_name='customerappraise',
            name='customer_logo',
            field=models.ImageField(upload_to='customers', verbose_name='客户LOGO'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mainPhoto',
            field=models.ImageField(upload_to='products', verbose_name='上传主图'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mainmanu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.MainManu', verbose_name='选择一级类目'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondarymanu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.SecondaryManu', verbose_name='选择二级类目'),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日期'),
        ),
    ]
