# Generated by Django 2.1.1 on 2018-10-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20181008_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerappraise',
            options={'verbose_name': '客户评价', 'verbose_name_plural': '客户评价'},
        ),
    ]
