# Generated by Django 2.1.1 on 2018-10-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20181008_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerappraise',
            name='customer_name',
            field=models.CharField(max_length=100, null=True, verbose_name='客户名称'),
        ),
    ]
