# Generated by Django 2.1.1 on 2018-10-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_customerappraise_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='问题描述')),
                ('answer', models.CharField(max_length=400, verbose_name='问题答案')),
            ],
            options={
                'verbose_name': '常见问题',
                'verbose_name_plural': '常见问题',
            },
        ),
    ]
